### DISCUSSION TITLE
How to use indexed colours with colour scheme

### DISCUSSION THREAD

**Discussion by dylan-hoefsloot** [wezterm/wezterm#1441] [Q&A] [answered]
I have been using the colour variable `indexed` as described in the documentation [here](https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors)

I have now defined a colour scheme and I am not sure how to continue to use indexed colours, whether that be as part of the colour scheme or seperately in the configuration.

Is this supported?

**Comment by wez** [comment]
The colors are used by applications emitting escape sequences around their output; there are quite a few documented in https://wezfurlong.org/wezterm/escape-sequences.html#graphic-rendition-sgr but the main ones are:

`CSI 30` through `CSI 37` set the foreground to index `0` through `7`, respectively. 
`CSI 40` through `CSI 47` set the background to index `0` through `7`, respectively. 

`CSI 90` through `CSI 97` set the foreground to index `8` through `15`, respectively. 
`CSI 100` through `CSI 107` set the background to index `8` through `15`, respectively. 

There are some extended sequences:

`CSI 38 : 5 : INDEX m` will set the foreground index to `INDEX` where `INDEX` is in the range `0-255`
`CSI 48 : 5 : INDEX m` will set the background index to `INDEX` where `INDEX` is in the range `0-255`

It is up to the applications that you use to emit these sequences in appropriate places.

In vim for example, you will typically configure a syntax highlighting scheme to use `ctermfg` and `ctermbg` and have those specify the palette indices, although with vim in particular, if `termguicolors` is set you can tell vim to use full RGB color specifiers in your color scheme rather than palette indices if you prefer.

**Reply by dylan-hoefsloot** [reply]
Sorry I dont think I phrased my question very well, I do know how the indexed colours are used by applications.

My question here is how do I set them in Wezterm if I am using a colour scheme.

I am able to set them and use them without a colour scheme by using the `colors` block but as soon as I use the `color_scheme` variable the indexed colours are no longer available.

**Reply by wez** [reply]
Oh the colors defined in the palette of your selected `color_scheme` take precedence over your `colors` configuration (this is noted in the [Color Scheme](https://wezfurlong.org/wezterm/config/appearance.html#color-scheme) docs.

You'll need to define your own copy of the color scheme you want to use with that extended palette.  Take a look at:

https://wezfurlong.org/wezterm/config/appearance.html#defining-a-color-scheme-in-your-weztermlua
and
https://wezfurlong.org/wezterm/config/appearance.html#defining-a-color-scheme-in-a-separate-file

**Reply by dylan-hoefsloot** [reply]
Yep, I went that route and made my own color scheme, however I wasnt sure how to add the indexed colours to that colour scheme as I couldnt find an example of anyone doing that.

I tried to use an array/list named `indexed` but that broke the colour scheme

**Reply by wez** [reply, marked as answer]
I'd suggest something like this if you're using a TOML file for the color scheme:

```toml
[colors]
foreground = "#bbbbbb"
background = "#000000"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#000000","#bb0000","#00bb00","#bbbb00","#0000bb","#bb00bb","#00bbbb","#bbbbbb"]
brights = ["#555555","#ff5555","#55ff55","#ffff55","#5555ff","#ff55ff","#55ffff","#ffffff"]

[colors.indexed]
136 = "orange"
```

```bash
printf "\x1b[48;5;136mI am 136\x1b[0m"
```
