### DISCUSSION TITLE
how to adjust each font weight separately?

### DISCUSSION THREAD

**Discussion by nupharr** [wezterm/wezterm#5511] [Q&A] [answered]
### What Operating System(s) are you running on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Ask your question!

Here is an example of Alacritty configuration, how to implement this in Wezterm?

```toml
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
```
