### ISSUE TITLE
vim color will change when move the cursor

### ISSUE THREAD

**Issue by Sherlock-Holo** [wezterm/wezterm#6634]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

when using the vim in wezterm, the color is changed unexpected

when open vim with a file, such as a shell script, the color is 

![Image](https://github.com/user-attachments/assets/ff360e57-b967-4fad-84cc-7573aef31b3b)

that's correct, but when I move the cursor, it will change

![Image](https://github.com/user-attachments/assets/1fade7e3-cc21-4da6-863e-bc545b1ec1de)

that doesn't happen in cosmic-terminal

![Image](https://github.com/user-attachments/assets/4af0f39b-7bc3-4db8-87a4-cda829016a26)

(the color has a little different but I think it is ok, if it doesn't change color suddenly when I move the cursor)

also in konsole it doesn't change too

![Image](https://github.com/user-attachments/assets/b86b437d-31ae-48c3-93a0-a44f49b1ad4e)

GNOME terminal doesn't change too

![Image](https://github.com/user-attachments/assets/e42d359c-3d8c-4ccc-91fd-29c37284023f)

### Configuration

```lua
local wezterm = require 'wezterm'
local act = wezterm.action

local mykeys = {}
for i = 1, 9 do
  -- ALT + number to activate that tab
  table.insert(mykeys, {
    key = tostring(i),
    mods = 'ALT',
    action = act.ActivateTab(i - 1),
  })
end

-- move tab
table.insert(mykeys, { key = '{', mods = 'SHIFT|ALT', action = act.MoveTabRelative(-1) })
table.insert(mykeys, { key = '}', mods = 'SHIFT|ALT', action = act.MoveTabRelative(1) })

-- switch active tab
table.insert(mykeys, { key = '[', mods = 'CTRL|ALT', action = act.ActivateTabRelative(-1) })
table.insert(mykeys, { key = ']', mods = 'CTRL|ALT', action = act.ActivateTabRelative(1) })

-- clear screen

-- Clears only the scrollback and leaves the viewport intact.
-- You won't see a difference in what is on screen, you just won't
-- be able to scroll back until you've output more stuff on screen.
-- This is the default behavior.
table.insert(mykeys, {
      key = 'K',
      mods = 'CTRL|SHIFT',
      action = act.ClearScrollback 'ScrollbackOnly',
    }
)
-- Clears the scrollback and viewport leaving the prompt line the new first line.
table.insert(mykeys, {
      key = 'K',
      mods = 'CTRL|SHIFT',
      action = act.ClearScrollback 'ScrollbackAndViewport',
    }
)
-- Clears the scrollback and viewport, and then sends CTRL-L to ask the
-- shell to redraw its prompt
table.insert(mykeys, {
      key = 'K',
      mods = 'CTRL|SHIFT',
      action = act.Multiple {
        act.ClearScrollback 'ScrollbackAndViewport',
        act.SendKey { key = 'L', mods = 'CTRL' },
      },
    }
)

-- ignore case search
table.insert(mykeys, { key = "f", mods = "CTRL|SHIFT", action = wezterm.action{ Search = { CaseInSensitiveString ="" }}})

-- show lanucher menu
table.insert(mykeys, {
      key = '=',
      mods = 'ALT',
      action = wezterm.action.ShowLauncher,
    }
)

return {
    keys = mykeys,

    window_padding = {
        left = 0,
        top = 0,
        bottom = '0.1cell',
    },

    enable_scroll_bar = true,

    animation_fps = 120,
    max_fps = 120,

    cursor_blink_rate = 900,
    default_cursor_style = 'BlinkingBlock',

    initial_rows = 42,
    initial_cols = 125,

    bold_brightens_ansi_colors = true,
    font = wezterm.font_with_fallback {
        'Cascadia Code PL',
        {family="Noto Sans CJK SC", weight="Medium"},
    },

    font_rules = {
        {
            intensity = 'Bold',
            italic = false,
            font = wezterm.font_with_fallback {
              {family="Cascadia Code PL", weight="Bold"},
              {family="Noto Sans CJK SC", weight="Bold"}
            },
        },
        {
            italic = true,
            font = wezterm.font_with_fallback {
              {family="Cascadia Code PL", weight="Bold", italic = true},
              {family="Noto Sans CJK SC", weight="Bold", italic = true}
            },
        },
    },

    font_size = 14,
--     font_antialias = 'Subpixel',

    color_scheme = 'My Solarized Dark',
    colors = {
        selection_fg = 'none',
        selection_bg = 'rgba(50% 50% 50% 50%)',
    },

    enable_wayland = false
}
```

### Expected Behavior

the color won't change when I move cursor

### Anything else?

my color config file is

```toml
# Solarized Dark Higher Contrast
[colors]
foreground = "#839496"
background = "#002B36"
cursor_bg = "#839294"
cursor_border = "#839294"
# cursor_fg = "#002831"

# ansi = ["#002831","#d11c24","#6cbe6c","#a57706","#2176c7","#c61c6f","#259286","#eae3cb"]
ansi = ["#002831","#d11c24","#6cbe6c","#C3A000","#2176c7","#75507B","#259286","#eae3cb"]
# brights = ["#006488","#f5163b","#51ef84","#b27e28","#178ec8","#e24d8e","#00b39e","#fcf4dc"]
brights = ["#006488","#f5163b","#51ef84","#b27e28","#719ECE","#e24d8e","#00b39e","#fcf4dc"]

[metadata]
name = 'My Solarized Dark'
```
