### ISSUE TITLE
Holding MEH key (Ctrl + Shift + Alt) and arrow key inputs extended unicode char when moving from Wezterm window to other text input field with GlazeWM on Windows 11

### ISSUE THREAD

**Issue by aodh66** [wezterm/wezterm#6753]
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

[GlazeWM](https://github.com/glzr-io/glazewm) on Windows

### WezTerm version

20250301-123420-7d0bff06

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Holding MEH key (Ctrl + Shift + Alt), and inputting an arrow key will input a unicode char when moving from the WezTerm windows. An example of this is the left arrow outputting `♠`, or right outputting `♦`. 

In my case my window manager is then moving the focus to the new window by doing this action, and the output unicode char goes into the new window.

### To Reproduce

To simply reproduce:
- Install [GlazeWM](https://github.com/glzr-io/glazewm/releases/tag/v3.8.1)
- Add the following binds to config.yaml in the keybinds section (On windows this is located at C:\Users\USERNAME\.glzr\glazewm\config.yaml)
```
keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['control+shift+alt+left']
  - commands: ['focus --direction right']
    bindings: ['control+shift+alt+right']
  - commands: ['focus --direction up']
    bindings: ['control+shift+alt+up']
  - commands: ['focus --direction down']
    bindings: ['control+shift+alt+down']
```
- Open notepad
- Open WezTerm
- Move focus from WezTerm to notepad with Ctrl + Shift + Alt + arrow key
- Unicode char should be output

This behaviour happens with the last arrow input, so starting with focus on the notepad window, moving to the WezTerm window, continuing to hold MEH, and then moving back to the notepad window will output the character for the arrow moving away from WezTerm.

### Configuration

no config

### Expected Behavior

I expected this action to move the focus from WezTerm to another without sending a unicode character, as no other program I have encountered does this.

### Logs

Debug Overlay
wezterm version: 20250301-123420-7d0bff06 x86_64-pc-windows-msvc
Window Environment: Windows
Lua Version: Lua 5.4
OpenGL: AMD Radeon RX 6800 XT 4.5.0 Core Profile Context 25.2.1.250206

### Anything else?

![Image](https://github.com/user-attachments/assets/fccbcec5-a9af-424b-b644-2126d4e91a05)
